[en]
  languageName = "English"
  weight = 1

[fr]
  languageName = "Français"
  weight = 2
  [fr.params]
    dateFormat = "02-01-2006"
    description = "Un thème de blog extrêmement rapide, réactif et riche en fonctionnalités pour Hugo"
    keywords = "Hugo, Bootstrap, Thème Blog"

[zh-cn]
  languageName = "简体中文"
  weight = 4
  [zh-cn.params]
    dateFormat = "2006-01-02"
    description = "Matt Blog"
    keywords = "Matt, Blog"
    [zh-cn.params.archive]
      dateFormat = "01-02"

[zh-tw]
  languageName = "繁體中文"
  weight = 3
  [zh-tw.params]
    dateFormat = "2006-01-02"
    description = "一個快速、響應式和功能豐富的 Hugo 博客主題"
    keywords = "Hugo, Bootstrap, 博客主題"
    [zh-tw.params.archive]
      dateFormat = "01-02"
