[[main]]
  name = "Support"
  identifier = "support"
  weight = 40
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/imattdu/myblog"
  weight = 1
[[main]]
  name = "Discussions"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/imattdu/myblog/discussions/new"
  weight = 2
[[main]]
  name = "Features Request"
  identifier = "feature-request"
  parent = "support"
  url = "https://github.com/imattdu/myblog/issues/new?template=feature_request.md"
  weight = 3
[[main]]
  parent = "support"
  weight = 4
  [main.params]
    divider = true

[[footer]]
  name = "Support"
  identifier = "support"
  weight = 1
[[footer]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/imattdu/myblog"
  weight = 1
  pre = '<i class="fab fa-fw fa-github"></i>'
[[footer]]
  name = "Discussions"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/imattdu/myblog/discussions/new"
  weight = 2
  pre = '<i class="fas fa-fw fa-comments"></i>'
[[footer]]
  name = "Features Request"
  identifier = "feature-request"
  parent = "support"
  url = "https://github.com/imattdu/myblog/issues/new?template=feature_request.md"
  weight = 3
[[footer]]
  name = "Bug Report"
  identifier = "bug-report"
  parent = "support"
  url = "https://github.com/imattdu/myblog/issues/new?template=bug_report.md"
  weight = 4

[[footer]]
  name = "Docs"
  identifier = "docs"
  weight = 2

[[footer]]
  name = "Features"
  identifier = "features"
  weight = 3

[[footer]]
  identifier = "link"
  name = "友情链接"
  weight = 4

